## data loading, function calling common to many front-ends.

library(rstan)
library(plyr)
library(psybayes)
library(ggplot2)
library(wutils)
library(xtable)

load(paste0(getwd(),'/output/data.Rdata'))

# final model samples (MCMC sampling) are generated by the final_results_model_sampler.R script. Run that before looking here.
load(paste0(getwd(),'/output/final_model_samples.RData'))

# extract permuted mcmc chains:
params <- extract(fit1,permuted=TRUE)
gamma <- 0.1
nSamples <- length(params$mu[,1,1])

# Helper functions-----------------------------------

linPred <- function(x,block,b1,b2,b3){
  eta <- b1 + b2*x + b3*block
}

p_pred <- function(eta){
  p_pred <- 1 / (1 + exp(-eta))
}
